name: 新アイテムのリクエスト
description: お気軽に追加ください *画像はIssueに添付してください
title: "[リクエスト]: "
labels: ["feature"]
projects: []

body:
  - type: input
    id: title
    attributes:
      label: タイトル
    validations:
      required: true

  - type: input
    id: href
    attributes:
      label: URL
    validations:
      required: false

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: tag
    validations:
      required: true
    attributes:
      label: タグ
      multiple: true
      options:
        - no-license-required
        - photo
        - illuste
        - icon
        - public-domain
        - video
        - free
